### ISSUE TITLE
Refactor database system

### ISSUE THREAD

**Issue by nhientruong04** [fuisl/checkin#41]
Create interface for connecting to local/global database, add more attributes and redesign table connection

**Comment by fuisl** [comment]
@nhientruong04 Here you can find the [link](https://drive.google.com/drive/u/3/folders/1bYjdHNSiJUl76CiYcm5LD8-RlmLB0txl) to our Excel ticket selling system.
> _please access this Drive folder with your school email as this is owned by presto@vgu.edu.vn_

### Description of the functionality

**1. Untitled form:**
- The form contains basic customers informations (e.g. name, id,...) and Seat
- Seat field is the most important. Since this will be use to display seating status on the final Seating map. There are some risks related to this field, one of those is incorrect grammar (it MUST be SPACE DELIMITED with the format: `B12 C11 A9`.

**2. TEST:**
- This sheet contains all the logical calculation behind the seating status.
- 3 main fields: timestamp, id and seat
  - Timestamp: use for status calculation. The status should change after some n minute(s) without confirmation from Presto.
  - id: primary key to identify customer
  - seat: destination for display.
- Sheet 1 calculate the status. Also, it supports confirming bought ticket with column `paid`.
- Sheet 2 Unpivot from space delimited data to column data.
- Sheet 4 query from Sheet 2 the seats that is either **Reserved** or **Paid** which are used to control the display on the next document.
> _Sheet 4 **MUST NOT** be change name since it is linked as it is._

**3. Map:**
- Import data from `TEST` to display.
- Use conditional formatting and `=COUNTIF(CELL) in the listed CELL > 0` _(if it exist in these column status, the color of the cell will change base on the conditions._


> **Please do take consider these notes**:
> - Seating and region? Do we sell seats or ticket to the regions (aka bán theo ghế hay theo khu vực) or hybrid between both models?
> - The deadline to this refactor project _(since right now we almost open our selling gate)_ 

Can you also give me an expected ship date for this database feature. That'd be helpful to know and to show some supports _(if needed)_

Do not hesitate to contact me or reply to this comment session. Many thanks.

**Comment by fuisl** [comment]
Refactored with #49
